AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dmc-front-sam-app

  Sample SAM Template for dmc-front-sam-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Tracing: Active
  Api:
    TracingEnabled: True

Parameters:
  APIBASEURL:
    Type: AWS::SSM::Parameter::Value<String>
    Default: 'API_BASE_URL'

Resources:
  DMCFrontendFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: index.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          API_BASE_URL: !Ref APIBASEURL

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DMCFrontendFunction:
    Description: "DMC Frontend Lambda Function ARN"
    Value: !GetAtt DMCFrontendFunction.Arn
  DMCFrontendFunctionIamRole:
    Description: "Implicit IAM Role created for DMC Frontend function"
    Value: !GetAtt DMCFrontendFunctionRole.Arn
  DMCFrontendFunctionUrl:
    Description: "Function URLs endpoint"
    Value: !GetAtt DMCFrontendFunctionUrl.FunctionUrl
